### ISSUE TITLE
Grammar inside index.html

### ISSUE THREAD

**Issue by Awentator** [maximilian-hack/website#2]
### Some possible grammar corections

I've also attached a corrected version of `index.html` if you may want to use it.
As both of the `index.html` of different languages are named the same and GitHub does not support `.html` files, I renamed them to `index-de-de.txt` and `index-en-uk.txt`.

**Corrected versions:**
[index-de-de.txt](https://github.com/maximilian-hack/website/files/12675333/index-de-de.txt)
[index-en-uk.txt](https://github.com/maximilian-hack/website/files/12675336/index-en-uk.txt)

### Corrections:
**About me**
- de-de: `h2` is not being translated into German _(corrected with "Über mich")_

**Education**
- de-de & en-uk: Only district of school is given, not entire location
  - en-uk: _(corrected with "Immanuel Kant Gymnasium, Münster, North Rhine-Westphalia, Germany")_
  - de-de: _(corrected with "Immanuel Kant Gymnasium, Münster, Nordrhein-Westfalen")_
- en-uk: "Major subjects" could also be named "Advanced courses" (more accurate English translation)
- en-uk: "Informatics" could also be named "IT"

**Other**
- en-uk: `div` to forward to German page "zur Deutschen Seite" could be renamed to "Zur deutschen Seite"

**Comment by maximilian-hack** [comment]
Thanks for submitting your Ideas and helping me with this project, I really appreciate it.
Your submited issue seems to be not that big of a deal, as GitHub works just fine with html files.
The same naming sceme of the index files is not a problem aswell, as the en-uk version is in another folder.
Furthermore, the missing translations were Intended, as these are commonly used in german everyday language and reffered to as "Anglizismen".
Regarding the seemingly not correct translated location of my school, I belive that you might have made a tiny mistake, as you seemingly have switched the german and english translation. Also, as far as my knowledge goes, "Westfahlen" does not have the letter "i" in it (you wrote "Westfahlien")
These seem to be just some minor mistakes, and I will try to implement the leftovers.
God work, keep it up!

**Comment by maximilian-hack** [comment]
Good news, this will be part of the next "update"! :)
